{"uuid":"8f3accb4-41fe-4e48-a620-6dfba7a6afcc","historyId":"158058b24b4a7a46d11996de94708369","fullName":"com.practice.Automation.login.DrPortalLogin.NegativeLogin","labels":[{"name":"package","value":"com.practice.Automation.login.DrPortalLogin"},{"name":"testClass","value":"com.practice.Automation.login.DrPortalLogin"},{"name":"testMethod","value":"NegativeLogin"},{"name":"parentSuite","value":"Full Regression suite"},{"name":"suite","value":"Incorrect password Test"},{"name":"subSuite","value":"com.practice.Automation.login.DrPortalLogin"},{"name":"host","value":"DESKTOP-P2H3HHA"},{"name":"thread","value":"159500@DESKTOP-P2H3HHA.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"NegativeLogin","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [Exception occurred while Authenticating doctor's login :] but found [Invalid Credentials]","trace":"java.lang.AssertionError: expected [Exception occurred while Authenticating doctor's login :] but found [Invalid Credentials]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat com.practice.Automation.login.DrPortalLogin.NegativeLogin(DrPortalLogin.java:80)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"ExpectedErrorMessage","value":"Exception occurred while Authenticating doctor's login :"},{"name":"password","value":"Truemeds@2023"},{"name":"username","value":"prasad.sartape@truemeds.i"}],"start":1742292900933,"stop":1742292903441}